/**
 * Render a Decomposition as Atlassian Document Format (ADF) — the body shape
 * Jira Cloud v3 expects for comments. Kept conservative: paragraphs, headings,
 * bullet lists, code marks. No tables, no inline-card embeds.
 *
 * Docs: https://developer.atlassian.com/cloud/jira/platform/apidocs/#api-rest-api-3-issue-issueIdOrKey-comment-post
 */

import type { AdfDoc } from "./jira.js";
import type { Decomposition, Subtask } from "./tech_decomp.js";

type AdfNode = { type: string; [k: string]: unknown };

function text(s: string): AdfNode {
  return { type: "text", text: s };
}

function code(s: string): AdfNode {
  return { type: "text", text: s, marks: [{ type: "code" }] };
}

function strong(s: string): AdfNode {
  return { type: "text", text: s, marks: [{ type: "strong" }] };
}

function paragraph(...nodes: AdfNode[]): AdfNode {
  return { type: "paragraph", content: nodes };
}

function heading(level: 1 | 2 | 3, content: string): AdfNode {
  return { type: "heading", attrs: { level }, content: [text(content)] };
}

function bulletList(items: AdfNode[][]): AdfNode {
  return {
    type: "bulletList",
    content: items.map((nodes) => ({
      type: "listItem",
      content: [{ type: "paragraph", content: nodes }],
    })),
  };
}

function rule(): AdfNode {
  return { type: "rule" };
}

function complexityLabel(c: Subtask["estimated_complexity"]): string {
  return c === "unknown" ? "" : ` · ${c}`;
}

function subtaskBlocks(st: Subtask, idx: number): AdfNode[] {
  const blocks: AdfNode[] = [];
  const headline = `${String(idx + 1).padStart(2, "0")} — ${st.title}${
    st.repo ? ` (${st.repo}${complexityLabel(st.estimated_complexity)})` : complexityLabel(st.estimated_complexity)
  }`;
  blocks.push(heading(3, headline));
  if (st.description) blocks.push(paragraph(text(st.description.trim())));
  if (st.files.length > 0) {
    const items: AdfNode[][] = st.files.map((f, i) => {
      const link = st.file_links[i];
      if (link) {
        return [
          {
            type: "text",
            text: f,
            marks: [{ type: "link", attrs: { href: link } }],
          } as AdfNode,
        ];
      }
      return [code(f)];
    });
    blocks.push(paragraph(strong("Files")));
    blocks.push(bulletList(items));
  }
  if (st.acceptance_criteria.length > 0) {
    blocks.push(paragraph(strong("Acceptance criteria")));
    blocks.push(bulletList(st.acceptance_criteria.map((a) => [text(a)])));
  }
  return blocks;
}

export function decompositionToAdf(opts: {
  d: Decomposition;
  adapter: string;
  model?: string;
  durationMs?: number;
}): AdfDoc {
  const { d, adapter, model, durationMs } = opts;
  const content: AdfNode[] = [];

  // Header line with the adapter / model / time so reviewers know what produced this.
  const headerBits: AdfNode[] = [
    text("Tech decomposition generated by "),
    code(adapter),
  ];
  if (model) {
    headerBits.push(text(" using "));
    headerBits.push(code(model));
  }
  if (typeof durationMs === "number" && durationMs > 0) {
    headerBits.push(text(` in ${(durationMs / 1000).toFixed(1)}s`));
  }
  headerBits.push(text("."));
  content.push(paragraph(...headerBits));
  content.push(rule());

  if (d.overview.trim()) {
    content.push(heading(2, "Overview"));
    content.push(paragraph(text(d.overview.trim())));
  }
  if (d.affected_repos.length > 0) {
    content.push(
      paragraph(
        strong("Affected repos: "),
        ...d.affected_repos.flatMap((r, i) => {
          const sep = i === 0 ? [] : [text(", ")];
          return [...sep, code(r)] as AdfNode[];
        }),
      ),
    );
  }

  content.push(heading(2, `Subtasks (${d.subtasks.length})`));
  d.subtasks.forEach((st, i) => {
    content.push(...subtaskBlocks(st, i));
  });

  if (d.risks.length > 0) {
    content.push(heading(2, `Risks (${d.risks.length})`));
    content.push(bulletList(d.risks.map((r) => [text(r)])));
  }
  if (d.open_questions.length > 0) {
    content.push(heading(2, `Open questions (${d.open_questions.length})`));
    content.push(bulletList(d.open_questions.map((q) => [text(q)])));
  }

  return { type: "doc", version: 1, content };
}
